export default {
  data: {
    items: [
      {
        idSalesOrderItem: null,
        unitGrossPrice: 0,
        sumGrossPrice: 0,
        taxRate: 0,
        productOptions: {},
        unitNetPrice: 0,
        sumNetPrice: 0,
        unitPrice: 0,
        sumPrice: 0,
        unitTaxAmountFullAggregation: null,
        sumTaxAmountFullAggregation: null,
        refundableAmount: null,
        canceledAmount: null,
        sumSubtotalAggregation: 0,
        unitSubtotalAggregation: null,
        unitProductOptionPriceAggregation: null,
        sumProductOptionPriceAggregation: null,
        unitExpensePriceAggregation: null,
        sumExpensePriceAggregation: null,
        unitDiscountAmountAggregation: null,
        sumDiscountAmountAggregation: null,
        unitDiscountAmountFullAggregation: null,
        sumDiscountAmountFullAggregation: null,
        unitPriceToPayAggregation: null,
        sumPriceToPayAggregation: null,
        taxRateAverageAggregation: null,
        taxAmountAfterCancellation: null,
        cartNote: null,
        id: 137,
        sku: '182740_concrete',
        groupKey: '182740_concrete',
        quantity: 45,
        calculatedDiscounts: {},
        abstractSku: '182740',
        maxQuantity: null,
        idDiscountPromotion: null,
        giftCardMetadata: null,
        forcedUnitGrossPrice: null,
        bundleItemIdentifier: null,
        relatedBundleItemIdentifier: null,
        images: [
          {
            idProductImage: 63,
            sortOrder: 1,
            externalUrlSmall: 'https://shop.w-f.ch/sonepar/asset_external/thumb/lieferanten/werma/bilder/961422366.jpg',
            externalUrlLarge: 'https://shop.w-f.ch/sonepar/asset_external/zoom/lieferanten/werma/bilder/961422366.jpg'
          }
        ],
        idProductAbstract: 137,
        name: 'Signalhupe 482 12VAC grau',
        productConcrete: null,
        concreteAttributes: [],
        quantitySalesUnit: null,
        idOrderItem: null,
        metadata: null,
        fkSalesOrder: null,
        fkOmsOrderItemState: null,
        process: null,
        variety: null,
        state: null,
        stateHistory: {},
        separator: null,
        unitTaxAmount: null,
        sumTaxAmount: null,
        lineNumber: null,
        markups: {}
      },
      {
        idSalesOrderItem: null,
        unitGrossPrice: 0,
        sumGrossPrice: 0,
        taxRate: 0,
        productOptions: {},
        unitNetPrice: 0,
        sumNetPrice: 0,
        unitPrice: 0,
        sumPrice: 0,
        unitTaxAmountFullAggregation: null,
        sumTaxAmountFullAggregation: null,
        refundableAmount: null,
        canceledAmount: null,
        sumSubtotalAggregation: 0,
        unitSubtotalAggregation: null,
        unitProductOptionPriceAggregation: null,
        sumProductOptionPriceAggregation: null,
        unitExpensePriceAggregation: null,
        sumExpensePriceAggregation: null,
        unitDiscountAmountAggregation: null,
        sumDiscountAmountAggregation: null,
        unitDiscountAmountFullAggregation: null,
        sumDiscountAmountFullAggregation: null,
        unitPriceToPayAggregation: null,
        sumPriceToPayAggregation: null,
        taxRateAverageAggregation: null,
        taxAmountAfterCancellation: null,
        cartNote: null,
        id: 2,
        sku: '15756_concrete',
        groupKey: '15756_concrete',
        quantity: 40,
        calculatedDiscounts: {},
        abstractSku: '15756',
        maxQuantity: null,
        idDiscountPromotion: null,
        giftCardMetadata: null,
        forcedUnitGrossPrice: null,
        bundleItemIdentifier: null,
        relatedBundleItemIdentifier: null,
        images: [
          {
            idProductImage: 1,
            sortOrder: 1,
            externalUrlSmall: 'https://shop.w-f.ch/sonepar/asset_external/thumb/lieferanten/panduit/bilder/227_dev_web_0227_csst-looped-b.jpg',
            externalUrlLarge: 'https://shop.w-f.ch/sonepar/asset_external/zoom/lieferanten/panduit/bilder/227_dev_web_0227_csst-looped-b.jpg'
          }
        ],
        idProductAbstract: 2,
        name: 'Kabelbinder PANDUIT 2,4×102mm transparent',
        productConcrete: null,
        concreteAttributes: [],
        quantitySalesUnit: null,
        idOrderItem: null,
        metadata: null,
        fkSalesOrder: null,
        fkOmsOrderItemState: null,
        process: null,
        variety: null,
        state: null,
        stateHistory: {},
        separator: null,
        unitTaxAmount: null,
        sumTaxAmount: null,
        lineNumber: null,
        markups: {}
      }
    ],
    totals: {
      subtotal: 145080,
      grandTotal: 0,
      netTotal: 0
    }
  },
  messages: [
    {
      type: 'add-to-cart',
      message: 'Produkte erfolgreich im Warenkorb',
      code: null,
      sources: [],
      meta: {
        product: {
          id: 1,
          name: 'Schriftbandkassette TC 9mm×7,7m rot-weiss',
          sku: 706128,
          quantity: 2,
          priceUnit: 100,
          priceGross: 3600,
          price: 6912,
          unitPriceGross: 3600,
          unitPrice: 6912,
          priceType: 1,
          priceTypeEndDate: null,
          relations: {
            consistsProducts: 0,
            productAlternative: 0,
            productNecessaryAccessory: 1,
            productReplacement: 0,
            productAccessory: 2,
            relatedProducts: 0,
          },
          eNumber: '941 151 361',
          url: 'product-detail',
          stocks: [
            {
              warehouseId: 5,
              stock: 3.00,
            },
            {
              warehouseId: 3,
              stock: 0.00,
            },
          ],
          image: {
            idProductImage: 1,
            externalUrlLarge: '/static/mock/dummy_square_1200--v1.jpg',
            externalUrlSmall: '/static/mock/dummy_square_500--v1.jpg',
            thumbs: [
              {
                absolutePath: '/static/mock/dummy_square_240--v1.jpg',
                width: 240,
                height: 240,
              }, {
                absolutePath: '/static/mock/dummy_square_500--v1.jpg',
                width: 500,
                height: 500,
              }, {
                absolutePath: '/static/mock/dummy_square_800--v1.jpg',
                width: 800,
                height: 800,
              }, {
                absolutePath: '/static/mock/dummy_square_1200--v1.jpg',
                width: 1200,
                height: 1200,
              },
            ],
          },
        },
      },
    }
  ]
};
