const erpProduct = {
  sku: '706127',
  quantity: 1,
  priceUnit: 123456,
  priceGross: 324,
  price: 1233,
  unitPriceGross: 324,
  unitPrice: 1233,
  priceType: 3,
  priceTypeEndDate: '30.1.2018',
  quantityOnHand: 1382,
  deliveryWarehouse: {
    warehouseId: 1,
    warehouseName: 'St. Gallen',
    stock: 30,
    iconDeliveryName: 'Wichtiger Text',
    iconDeliveryId: 'delivery004',
    iconPickupName: null,
    iconPickupId: null,
    text: 'Artikel ist lieferbar',
    idRule: 5,
  },
  pickupWarehouse: {
    warehouseId: 1,
    warehouseName: 'St. Gallen',
    stock: 4,
    iconDeliveryName: 'Wichtiger Text',
    iconDeliveryId: 'delivery001',
    iconPickupName: null,
    iconPickupId: null,
    text: 'Artikel ist abholbar',
    additionalText: 'Spezieller zusatztext',
    idRule: 5,
  },
  additionalWarehouses: [
    {
      warehouseId: 15,
      additionalText: 'availability.additional_text.5',
      iconDeliveryId: 'delivery003',
      iconDeliveryName: 'Nicht lieferbar',
      iconPickupId: 'pickup003',
      iconPickupName: 'in Kürze abholbar',
      idRule: 5,
      stock: 50,
      text: 'Dieser Artikel ist nicht lieferbar.',
      warehouseName: 'Colombier',
    },
    {
      warehouseId: 3,
      additionalText: 'availability.additional_text.5',
      iconDeliveryId: 'delivery002',
      iconDeliveryName: 'Nicht lieferbar',
      iconPickupId: 'pickup001',
      iconPickupName: 'Abholbar',
      idRule: 5,
      stock: 20,
      text: 'Dieser Artikel ist lieferbar.',
      warehouseName: 'Colombier',
    },
    {
      warehouseId: 3,
      additionalText: 'availability.additional_text.5',
      iconPickupId: 'pickup002',
      iconPickupName: 'in Kürze abholbar',
      idRule: 5,
      stock: 20,
      warehouseName: 'Spezielles Lager',
    },
    {
      warehouseId: 2,
      additionalText: 'availability.additional_text.5',
      iconDeliveryId: 'delivery001',
      iconDeliveryName: 'Nicht lieferbar',
      iconPickupId: null,
      iconPickupName: null,
      idRule: 5,
      stock: 0,
      text: 'Dieser Artikel ist lieferbar.',
      warehouseName: 'Colombier',
    },
  ],
};

export default {
  start: {
    data: {
      products: [
        {
          ...erpProduct,
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery001',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: `Spezieller zusatztext der unter ganze speziellen Umständen auch etwas länger ausfallen kann.
             Vermutlich wirklich lange`,
            idRule: 5,
          },
        },
        {
          ...erpProduct,
          sku: '706128',
          priceUnit: 123456,
          priceGross: 234563,
          price: 345678,
          unitPriceGross: 234550,
          unitPrice: 345655,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 1332,
          deliveryWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 30,
            iconDeliveryName: null,
            iconDeliveryId: null,
            iconPickupName: 'Abholbar',
            iconPickupId: 'pickup001',
            text: 'Artikel ist lieferbar',
            additionalText: 'Ganz spezieller text',
            idRule: 5,
          },
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: null,
            iconDeliveryId: null,
            iconPickupName: 'Abholbar',
            iconPickupId: 'pickup001',
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          additionalWarehouses: [
            {
              warehouseId: 15,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery003',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup002',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist nicht lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 3,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery002',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 2220,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 2,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery001',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup004',
              iconPickupName: 'nicht abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
          ],
        },
        {
          ...erpProduct,
          sku: '706126',
          priceUnit: 145,
          priceGross: 244,
          price: 2441,
          unitPriceGross: 244,
          unitPrice: 2441,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 182,
          deliveryWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 30,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist lieferbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
        },
        {
          ...erpProduct,
          sku: '706130',
        },
        {
          ...erpProduct,
          sku: '706131',
          priceUnit: 145,
          priceGross: 2344,
          price: 2381,
          unitPriceGross: 2344,
          unitPrice: 2381,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 182,
        },
        {
          ...erpProduct,
          sku: '706132',
          quantity: 1,
          priceUnit: 145,
          priceGross: 2231,
          price: 2423,
          unitPriceGross: 2231,
          unitPrice: 2423,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 182,
        },
        {
          ...erpProduct,
          sku: '706133',
        },
        {
          ...erpProduct,
          sku: '706134',
        },
        {
          ...erpProduct,
          sku: '706135',
        },
        {
          ...erpProduct,
          sku: '706136',
          quantity: 1,
          priceUnit: 145,
          priceGross: 1232,
          price: 1555,
          unitPriceGross: 1232,
          unitPrice: 1555,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 182,
        },
      ],
    },
  },
  relations: {
    data: {
      products: [
        {
          ...erpProduct,
          sku: '1231231',
          quantity: 1,
          priceUnit: 333,
          priceGross: 1124,
          price: 1141,
          unitPriceGross: 1124,
          unitPrice: 1141,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 1383,
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          additionalWarehouses: [
            {
              warehouseId: 15,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery003',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist nicht lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 3,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery002',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup001',
              iconPickupName: 'Abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 2,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery001',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup002',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
          ],
        },
        {
          ...erpProduct,
          sku: '1231232',
          quantity: 1,
          priceUnit: 333,
          priceGross: 334,
          price: 2441,
          unitPriceGross: 334,
          unitPrice: 2441,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 3254,
          deliveryWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 30,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist lieferbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'pickup001',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          additionalWarehouses: [
            {
              warehouseId: 15,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery003',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup002',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist nicht lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 3,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery002',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 2,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery001',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup004',
              iconPickupName: 'nicht abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
          ],
        },
        {
          ...erpProduct,
          sku: '1231233',
          quantity: 1,
          priceUnit: 333,
          priceGross: 750,
          price: 790,
          unitPriceGross: 750,
          unitPrice: 790,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 13823,
          deliveryWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 30,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist lieferbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'pickup001',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          additionalWarehouses: [
            {
              warehouseId: 15,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery003',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist nicht lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 3,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery002',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup001',
              iconPickupName: 'Abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 2,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery001',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup002',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
          ],
        },
        {
          ...erpProduct,
          sku: '1231122',
          quantity: 1,
          priceUnit: 333,
          priceGross: 7150,
          price: 7933,
          unitPriceGross: 7150,
          unitPrice: 7933,
          priceType: 3,
          priceTypeEndDate: '30.1.2018',
          quantityOnHand: 135,
          deliveryWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 30,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist lieferbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'pickup001',
            iconPickupName: 'Abholbar',
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          additionalWarehouses: [
            {
              warehouseId: 15,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery003',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist nicht lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 3,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery002',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup004',
              iconPickupName: 'nicht abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 2,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery001',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
          ],
        },
        {
          ...erpProduct,
          sku: '1231244',
          quantity: 1,
          priceUnit: 333,
          priceGross: 2150,
          price: 2933,
          unitPriceGross: 2150,
          unitPrice: 2933,
          priceType: 4,
          priceTypeEndDate: '31.1.2018',
          quantityOnHand: 5382,
          deliveryWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 30,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'delivery004',
            iconPickupName: null,
            iconPickupId: null,
            text: 'Artikel ist lieferbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          pickupWarehouse: {
            warehouseId: 1,
            warehouseName: 'St. Gallen',
            stock: 4,
            iconDeliveryName: 'Wichtiger Text',
            iconDeliveryId: 'pickup001',
            iconPickupName: 'Abholbar',
            iconPickupId: null,
            text: 'Artikel ist abholbar',
            additionalText: 'Spezieller zusatztext',
            idRule: 5,
          },
          additionalWarehouses: [
            {
              warehouseId: 15,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery003',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup001',
              iconPickupName: 'Abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist nicht lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 3,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery002',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup002',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
            {
              warehouseId: 2,
              additionalText: 'availability.additional_text.5',
              iconDeliveryId: 'delivery001',
              iconDeliveryName: 'Nicht lieferbar',
              iconPickupId: 'pickup003',
              iconPickupName: 'in Kürze abholbar',
              idRule: 5,
              stock: 0,
              text: 'Dieser Artikel ist lieferbar.',
              warehouseName: 'Colombier',
            },
          ],
        },
        {
          ...erpProduct,
          sku: '706128',
        },
        {
          ...erpProduct,
          sku: '706129',
        },
        {
          ...erpProduct,
          sku: '706130',
        },
        {
          ...erpProduct,
          sku: '706131',
        },
        {
          ...erpProduct,
          sku: '111111',
        },
      ],
    },
  },
};
